sudo: required
services:
  - docker
language: python
python:
  - 3.6
before_install:
  - wget https://github.com/mozilla/geckodriver/releases/download/v0.20.1/geckodriver-v0.20.1-linux64.tar.gz
  - mkdir geckodriver
  - tar -xzf geckodriver-v0.20.1-linux64.tar.gz -C geckodriver
  - export PATH=$PATH:$PWD/geckodriver
  - echo "$DOCKER_PASSWORD" | docker login --username "$DOCKER_USERNAME" --password-stdin
  - docker build -t "$DOCKER_USERNAME"/clinical-trials-analysis:latest .
  - docker run "$DOCKER_USERNAME"/clinical-trials-analysis:latest bash -c "cd clinical-trials-analysis; pytest"
install:
  - pip install -r requirements.txt
script:
  - pytest
addons:
  firefox: latest
after_script:
  - docker push chtka/clinical-trials-analysis:latest
  - pip install awscli
  - eval $(aws ecr get-login --no-include-email)
  - docker tag chtka/clinical-trials-analysis:latest ${AWS_ID}.dkr.ecr.us-west-1.amazonaws.com/benl/clinical-trials-analysis
  - docker push ${AWS_ID}.dkr.ecr.us-west-1.amazonaws.com/benl/clinical-trials-analysis
  - aws s3 cp `pwd`/cfn_template.yml s3://${CT_ANALYSIS_DEPLOY_BUCKET_NAME}/cfn/cfn_template.yml