sudo: required
services:
  - docker
language: python
python:
  - 3.6
before_install:
  - wget https://github.com/mozilla/geckodriver/releases/download/v0.21.0/geckodriver-v0.21.0-linux64.tar.gz
  - mkdir geckodriver
  - tar -xzf geckodriver-v0.21.0-linux64.tar.gz -C geckodriver
  - export PATH=$PATH:$PWD/geckodriver
  - echo "$DOCKER_PASSWORD" | docker login --username "$DOCKER_USERNAME" --password-stdin
  - docker build -t chtka/clinical-trials-analysis:latest .
  - docker run chtka/clinical-trials-analysis:latest bash -c "cd clinical-trials-analysis; pytest"
install:
  - pip install -r requirements.txt
script:
  - pytest
addons:
  firefox: latest
after_script:
  - docker push chtka/clinical-trials-analysis:latest