version: 0.2
phases:
  install:
    commands:
      - apt-get update
      - apt-get upgrade -y
      - apt-get install -y firefox
      - wget https://github.com/mozilla/geckodriver/releases/download/v0.20.1/geckodriver-v0.20.1-linux64.tar.gz
      - mkdir geckodriver
      - tar -xzf geckodriver-v0.20.1-linux64.tar.gz -C geckodriver
      - export PATH=$PATH:$PWD/geckodriver
      - pip install -r requirements.txt
  build:
    commands:
      - echo Build started on `date`
      - echo Running tests locally...
      - pytest
      - echo Building Docker image...
      - docker build -t $IMAGE_REPO_NAME:$IMAGE_TAG . 
      - echo Running tests in Docker container...
      - docker run $IMAGE_REPO_NAME:$IMAGE_TAG bash -c "cd clinical-trials-analysis; pytest"
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Logging in to Amazon ECR...
      - $(aws ecr get-login --no-include-email)
      - echo Pushing the Docker image...
      - docker tag $IMAGE_REPO_NAME:$IMAGE_TAG $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME:$IMAGE_TAG
      - docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME:$IMAGE_TAG